[project]
name = "openai-nicegui-chat"
version = "0.1.0"
description = "OpenAI Chat with a NiceGUI UI "
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.21",
    "langchain-community>=0.3.20",
    "langchain-openai>=0.3.9",
    "nicegui>=2.13.0",
]
